### ISSUE TITLE
Additional Features

### ISSUE THREAD

**Issue by Neotamandua** [ZitaneLabs/hdrop#7]
**General:**
- Page Zoom skews the website proportions

**File Share Page:**
- [ ] Checkboxes to randomize filename, clear metadata
> It's not possible to strip metadata from encrypted file. Needs discussion at which step this functionality can be implemented with proper user experience
- [x] Button to delete the file directly, not only change expiration time
- [x] Option to copy download-link with or without password (never show password directly), but keep second password field

**System Design:**
- [x] Modular & agnostic approach for storage medium (Have different API modules for S3, direct storage etc.)

**Low priority:**
- [x] Show text content directly (optionally with syntax highlighting like pastebin)

**Comment by SplittyDev** [comment]
I'm closing this, since all concerns are essentially fixed in the latest version (except the filename randomization, which can be a separate feature if we really want it).
